/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.awt.Color;

/**
 *
 * @author User
 */
public class customerTrainingSessionDetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form customerTrainingSessionForm
     */
    private Gym APUGym;
    private Customer cust_acc;
    private TrainingSession ts_details;
    
    public customerTrainingSessionDetailsForm(Gym APUGym, Customer cust_acc, TrainingSession ts_details) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        getContentPane().setBackground(Color.WHITE);
        this.APUGym = APUGym;
        this.cust_acc = cust_acc;
        this.ts_details = ts_details;
        trainingSessionID.setText(ts_details.getTrainingSessionID());
        trainingSessionName.setText(ts_details.getTrainingSessionName());
        trainingSessionTrainerName.setText(ts_details.getTrainerName(APUGym.getTrainers()));
        trainingSessionDate.setText(ts_details.getTrainingSessionDate());
        trainingSessionTime.setText(ts_details.getTrainingSessionDuration());
        trainingSessionLevel.setText(ts_details.getTrainingSessionLevel());
        String status = ts_details.getTrainingSessionStatus();
        trainingSessionStatus.setText(status);
        if(status.equals("Not Started")){
            trainingSessionMessage.setText("You have been registered for this training session. We hope to see you soon!");
        } else if(status.equals("Completed")){
            trainingSessionMessage.setText("You have completed this training session. Good job and thank you for coming!");
        } else if(status.equals("Cancelled")){
            trainingSessionMessage.setText("The training session has been cancelled. Sorry for any inconvenience caused.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBut = new javax.swing.JButton();
        feedbackBut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        trainingSessionStatus = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        trainingSessionTrainerName = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        trainingSessionDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        trainingSessionTime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        trainingSessionLevel = new javax.swing.JLabel();
        trainingSessionMessage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        trainingSessionName = new javax.swing.JLabel();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        trainingSessionID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnBut.setText("Return to Training Sessions");
        returnBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButActionPerformed(evt);
            }
        });

        feedbackBut.setText("Submit Feedback");
        feedbackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackButActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        trainingSessionStatus.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        trainingSessionStatus.setText("Not Started");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel6.setText("Trainer: ");

        trainingSessionTrainerName.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        trainingSessionTrainerName.setText("Jordan Yeoh");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel8.setText("Date:");

        trainingSessionDate.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        trainingSessionDate.setText("20/5/2022");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel10.setText("Time:");

        trainingSessionTime.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        trainingSessionTime.setText("5.00 p.m. - 6.00 p.m.");

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel12.setText("Level:");

        trainingSessionLevel.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        trainingSessionLevel.setText("Beginner");

        trainingSessionMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        trainingSessionMessage.setText("You have been registered for this training session. We hope to see you soon!");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jLabel14.setText("Status:");

        trainingSessionName.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        trainingSessionName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainingSessionName.setText("Full-Body Workout for Beginners");
        trainingSessionName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainingSessionMessage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel8))
                                                .addComponent(jLabel12)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trainingSessionLevel)
                                    .addComponent(trainingSessionTrainerName)
                                    .addComponent(trainingSessionDate)
                                    .addComponent(trainingSessionTime)
                                    .addComponent(trainingSessionStatus))
                                .addGap(45, 45, 45))
                            .addComponent(trainingSessionName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(trainingSessionName, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(trainingSessionTrainerName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(trainingSessionDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(trainingSessionTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(trainingSessionLevel))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(trainingSessionStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(trainingSessionMessage)
                .addGap(33, 33, 33))
        );

        jLayeredPane8.setBackground(new java.awt.Color(255, 102, 102));
        jLayeredPane8.setForeground(new java.awt.Color(102, 255, 102));
        jLayeredPane8.setOpaque(true);

        trainingSessionID.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        trainingSessionID.setForeground(new java.awt.Color(255, 255, 255));
        trainingSessionID.setText("TS 059457");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/register.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Training Session #");

        jLayeredPane8.setLayer(trainingSessionID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane8.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainingSessionID)
                .addContainerGap(260, Short.MAX_VALUE))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trainingSessionID)
                    .addComponent(jLabel17))
                .addGap(30, 30, 30))
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane8)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(returnBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(feedbackBut))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feedbackBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButActionPerformed
        // TODO add your handling code here:
        new customerTrainingSessionForm(APUGym, cust_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButActionPerformed

    private void feedbackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackButActionPerformed
        // TODO add your handling code here:
        new customerTrainingSessionFeedbackForm(APUGym, cust_acc, ts_details).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_feedbackButActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton feedbackBut;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnBut;
    private javax.swing.JLabel trainingSessionDate;
    private javax.swing.JLabel trainingSessionID;
    private javax.swing.JLabel trainingSessionLevel;
    private javax.swing.JLabel trainingSessionMessage;
    private javax.swing.JLabel trainingSessionName;
    private javax.swing.JLabel trainingSessionStatus;
    private javax.swing.JLabel trainingSessionTime;
    private javax.swing.JLabel trainingSessionTrainerName;
    // End of variables declaration//GEN-END:variables
}
