/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class customerMenuForm extends javax.swing.JFrame {

    /**
     * Creates new form customerMenuForm
     */
    private Gym APUGym;
    private Customer cust_acc;
    
    public customerMenuForm(Gym APUGym, Customer cust_acc) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        getContentPane().setBackground(Color.WHITE);
        this.APUGym = APUGym;
        this.cust_acc = cust_acc;
        customerName.setText(cust_acc.getUserName());
        customerID.setText(cust_acc.getUserID());
        customerPhoneNumber.setText("Contact: " + cust_acc.getUserPhoneNumber());
        customerJoinDate.setText("Joined Date: " + cust_acc.getUserJoinDate());
        customerFitnessLevel.setText(cust_acc.getCustomerFitnessLevel() + " Level");
        customerSubscriptionPlan.setText(cust_acc.getCustomerSubscriptionPlan() + " Plan");
        
        ArrayList<TrainingSession> TrainingSessions = APUGym.getTrainingSessions();
        TrainingSession ts = null;
        for(int i = TrainingSessions.size() - 1; i >= 0; i--){
            if(Arrays.asList(TrainingSessions.get(i).getCustomerID()).contains(cust_acc.getUserID())){
                ts = TrainingSessions.get(i);
                break;
            }
        }
        if(ts == null){
            customerTrainingSessionName.setText("No Training Session Found.");
            customerTrainingSessionDate.setText("Date: - ");
            customerTrainingSessionDuration.setText("Duration: - ");
        } else{
            customerTrainingSessionName.setText(ts.getTrainingSessionName());
            customerTrainingSessionDate.setText("Date: " + ts.getTrainingSessionDate());
            customerTrainingSessionDuration.setText("Duration: " + ts.getTrainingSessionDuration());
        }
        
        double customerPaymentPayableAmount = 0;
        for(Payment payment: APUGym.getPayments()){
            if(payment.getCustomerID().equals(cust_acc.getUserID()) && payment.getPaymentStatus().equals("Pending")){
                customerPaymentPayableAmount += payment.getPaymentAmount();
            }
        }
        customerPaymentPayable.setText("Payable: RM " + String.format("%.2f", customerPaymentPayableAmount));
        customerPaymentPaid.setText("Paid: RM " + String.format("%.2f", cust_acc.getCustomerTotalSpending()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        homeBut = new javax.swing.JLabel();
        logoutBut = new javax.swing.JButton();
        customerID = new javax.swing.JLabel();
        customerName = new javax.swing.JLabel();
        customerJoinDate = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        customerFitnessLevel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        customerSubscriptionPlanBut = new javax.swing.JLayeredPane();
        customerSubscriptionPlan = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkBut = new javax.swing.JButton();
        payBut = new javax.swing.JButton();
        customerTrainingSessionName = new javax.swing.JLabel();
        customerTrainingSessionDate = new javax.swing.JLabel();
        customerTrainingSessionDuration = new javax.swing.JLabel();
        customerPaymentPayable = new javax.swing.JLabel();
        customerPaymentPaid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        customerPhoneNumber = new javax.swing.JLabel();
        editBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 102, 102));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jLayeredPane1.setForeground(new java.awt.Color(102, 255, 102));
        jLayeredPane1.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Welcome to Customer Menu");

        homeBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/home logo.png"))); // NOI18N

        logoutBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/logout.png"))); // NOI18N
        logoutBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        logoutBut.setBorderPainted(false);
        logoutBut.setContentAreaFilled(false);
        logoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(homeBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(logoutBut, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBut)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBut)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeBut)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(logoutBut)
                        .addComponent(jLabel3)))
                .addGap(9, 9, 9))
        );

        customerID.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        customerID.setText("CU059457");

        customerName.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        customerName.setForeground(new java.awt.Color(102, 102, 102));
        customerName.setText("TAN ZHI JUN");

        customerJoinDate.setText("Joined Date: 20 March 2020");

        jLayeredPane2.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane2.setOpaque(true);

        customerFitnessLevel.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        customerFitnessLevel.setForeground(new java.awt.Color(255, 255, 255));
        customerFitnessLevel.setText("Beginner Level");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/level.png"))); // NOI18N

        jLayeredPane2.setLayer(customerFitnessLevel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerFitnessLevel)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(customerFitnessLevel))
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        customerSubscriptionPlanBut.setBackground(new java.awt.Color(0, 0, 0));
        customerSubscriptionPlanBut.setOpaque(true);
        customerSubscriptionPlanBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerSubscriptionPlanButMouseClicked(evt);
            }
        });

        customerSubscriptionPlan.setFont(new java.awt.Font("Agency FB", 1, 25)); // NOI18N
        customerSubscriptionPlan.setForeground(new java.awt.Color(255, 255, 255));
        customerSubscriptionPlan.setText("Elite Plan");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/plan.png"))); // NOI18N

        customerSubscriptionPlanBut.setLayer(customerSubscriptionPlan, javax.swing.JLayeredPane.DEFAULT_LAYER);
        customerSubscriptionPlanBut.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout customerSubscriptionPlanButLayout = new javax.swing.GroupLayout(customerSubscriptionPlanBut);
        customerSubscriptionPlanBut.setLayout(customerSubscriptionPlanButLayout);
        customerSubscriptionPlanButLayout.setHorizontalGroup(
            customerSubscriptionPlanButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerSubscriptionPlanButLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(26, 26, 26)
                .addComponent(customerSubscriptionPlan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerSubscriptionPlanButLayout.setVerticalGroup(
            customerSubscriptionPlanButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerSubscriptionPlanButLayout.createSequentialGroup()
                .addGroup(customerSubscriptionPlanButLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerSubscriptionPlanButLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(customerSubscriptionPlan))
                    .addGroup(customerSubscriptionPlanButLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Dashboard");

        jLayeredPane4.setBackground(new java.awt.Color(255, 204, 204));
        jLayeredPane4.setForeground(new java.awt.Color(102, 255, 102));
        jLayeredPane4.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 20)); // NOI18N
        jLabel16.setText("Traning Sessions");

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 20)); // NOI18N
        jLabel17.setText("Payment");

        checkBut.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        checkBut.setText("Check");
        checkBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkButActionPerformed(evt);
            }
        });

        payBut.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        payBut.setText("Pay");
        payBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButActionPerformed(evt);
            }
        });

        customerTrainingSessionName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        customerTrainingSessionName.setForeground(new java.awt.Color(204, 0, 0));
        customerTrainingSessionName.setText("Yoga Session with Jordan");

        customerTrainingSessionDate.setText("Date: 16 May 2022");

        customerTrainingSessionDuration.setText("Duration: 2.00pm - 4.00pm");

        customerPaymentPayable.setText("Payable:");

        customerPaymentPaid.setText("Paid:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/mini logo.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane4.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(checkBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(payBut, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(customerTrainingSessionName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(customerTrainingSessionDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(customerTrainingSessionDuration, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(customerPaymentPayable, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(customerPaymentPaid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(checkBut, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(customerTrainingSessionDate)
                            .addComponent(customerTrainingSessionDuration)
                            .addComponent(customerTrainingSessionName, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(payBut, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(customerPaymentPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(customerPaymentPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addContainerGap())))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(customerPaymentPayable))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(customerTrainingSessionName))))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTrainingSessionDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerTrainingSessionDuration))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(customerPaymentPaid)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBut)
                    .addComponent(payBut))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerPhoneNumber.setText("Contact: 016-3099309");

        editBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/edit.png"))); // NOI18N
        editBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editBut.setBorderPainted(false);
        editBut.setContentAreaFilled(false);
        editBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLayeredPane4)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editBut)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerName)
                            .addComponent(customerID)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerJoinDate)
                            .addComponent(customerPhoneNumber))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(customerSubscriptionPlanBut)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editBut)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(customerName)
                                .addGap(6, 6, 6)
                                .addComponent(customerID)))
                        .addGap(11, 11, 11)
                        .addComponent(customerJoinDate)
                        .addGap(9, 9, 9)
                        .addComponent(customerPhoneNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(customerSubscriptionPlanBut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jLabel15)
                .addGap(11, 11, 11)
                .addComponent(jLayeredPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkButActionPerformed
        // TODO add your handling code here:
        new customerTrainingSessionForm(APUGym, cust_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkButActionPerformed

    private void payButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButActionPerformed
        // TODO add your handling code here:
        new customerPaymentForm(APUGym, cust_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_payButActionPerformed

    private void logoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButActionPerformed
        // TODO add your handling code here:
        int input = JOptionPane.showConfirmDialog(null, "Are you Sure?");
        if(input==0)
        {
            APUGym.saveAllRecords();
            new startForm(APUGym).setVisible(true);
            this.dispose();
        }else
        {
            JOptionPane.getRootFrame().dispose();
        }
    }//GEN-LAST:event_logoutButActionPerformed

    private void editButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButActionPerformed
        // TODO add your handling code here:
        new customerProfileForm(APUGym, cust_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editButActionPerformed

    private void customerSubscriptionPlanButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerSubscriptionPlanButMouseClicked
        // TODO add your handling code here:
        new customerSubscriptionForm(APUGym, cust_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerSubscriptionPlanButMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkBut;
    private javax.swing.JLabel customerFitnessLevel;
    private javax.swing.JLabel customerID;
    private javax.swing.JLabel customerJoinDate;
    private javax.swing.JLabel customerName;
    private javax.swing.JLabel customerPaymentPaid;
    private javax.swing.JLabel customerPaymentPayable;
    private javax.swing.JLabel customerPhoneNumber;
    private javax.swing.JLabel customerSubscriptionPlan;
    private javax.swing.JLayeredPane customerSubscriptionPlanBut;
    private javax.swing.JLabel customerTrainingSessionDate;
    private javax.swing.JLabel customerTrainingSessionDuration;
    private javax.swing.JLabel customerTrainingSessionName;
    private javax.swing.JButton editBut;
    private javax.swing.JLabel homeBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBut;
    private javax.swing.JButton payBut;
    // End of variables declaration//GEN-END:variables
}
