      
package oodj_assignment;

import java.awt.Color;

public class startForm extends javax.swing.JFrame {

    /**
     * Creates new form startForm
     */
    private Gym APUGym;
    
    public startForm(Gym APUGym) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        getContentPane().setBackground(Color.WHITE);
        this.APUGym = APUGym;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        managerBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        custBut = new javax.swing.JButton();
        trainerBut = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 51, 255));
        setBounds(new java.awt.Rectangle(700, 600, 500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Developed by: Kelwin and Kenneth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 470, -1, -1));

        managerBut.setBackground(new java.awt.Color(255, 51, 51));
        managerBut.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        managerBut.setForeground(new java.awt.Color(255, 255, 255));
        managerBut.setText("LOGIN AS MANAGER");
        managerBut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        managerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButActionPerformed(evt);
            }
        });
        getContentPane().add(managerBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 374, 199, 78));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/new logo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 15, 211, 204));

        custBut.setBackground(new java.awt.Color(255, 51, 51));
        custBut.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        custBut.setForeground(new java.awt.Color(255, 255, 255));
        custBut.setText("LOGIN AS CUSTOMER");
        custBut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        custBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custButActionPerformed(evt);
            }
        });
        getContentPane().add(custBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 282, 407, 84));

        trainerBut.setBackground(new java.awt.Color(255, 51, 51));
        trainerBut.setFont(new java.awt.Font("Calibri", 1, 22)); // NOI18N
        trainerBut.setForeground(new java.awt.Color(255, 255, 255));
        trainerBut.setText("LOGIN AS TRAINER");
        trainerBut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        trainerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerButActionPerformed(evt);
            }
        });
        getContentPane().add(trainerBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 374, 202, 78));

        jLayeredPane1.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane1.setForeground(new java.awt.Color(255, 153, 51));
        jLayeredPane1.setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("APU GYM MANAGEMENT SYSTEM");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 480, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/gym (1).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButActionPerformed
        new managerLoginForm(APUGym).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerButActionPerformed

    private void custButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custButActionPerformed
        new customerLoginForm(APUGym).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_custButActionPerformed

    private void trainerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerButActionPerformed
        new trainerLoginForm(APUGym).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trainerButActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton custBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton managerBut;
    private javax.swing.JButton trainerBut;
    // End of variables declaration//GEN-END:variables
}
