/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj_assignment;

import java.util.*;
import java.awt.Color;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;

public class trainerAssignedCustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form customerTrainingSessionForm
     */
    Gym APUGym;
    Trainer tr_acc;
    
    public trainerAssignedCustomerForm(Gym APUGym, Trainer tr_acc) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        getContentPane().setBackground(Color.WHITE);
        this.APUGym = APUGym;
        this.tr_acc = tr_acc;
        
        ArrayList<Customer> assignedCustomers = new ArrayList();
        String[] assignedCustomersID = tr_acc.getTrainerCustomerID();
        assignedCustomersNum.setText(String.valueOf(assignedCustomersID.length));
        for(String ID: assignedCustomersID){
            for(Customer cust: APUGym.getCustomers()){
                if(cust.getUserID().equals(ID)){
                    assignedCustomers.add(cust);
                }
            }
        }
        assignedCustomersTable.setRowHeight(35);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        assignedCustomersTable.setDefaultRenderer(String.class, centerRenderer);
        DefaultTableModel feedbackModel = (DefaultTableModel) assignedCustomersTable.getModel();
        for(Customer cust: assignedCustomers){
            feedbackModel.addRow(new Object[]{cust.getUserID(), cust.getUserName(), 
                cust.getUserEmail(), cust.getUserPhoneNumber(), 
                cust.getCustomerFitnessLevel()});
        }
        
        TableRowSorter<TableModel> assignedCustomersRowSorter = new TableRowSorter<>(assignedCustomersTable.getModel());
        assignedCustomersTable.setRowSorter(assignedCustomersRowSorter);
        assignedCustomersSearchField.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = assignedCustomersSearchField.getText();

                if (text.trim().length() == 0) {
                    assignedCustomersRowSorter.setRowFilter(null);
                } else {
                    assignedCustomersRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = assignedCustomersSearchField.getText();

                if (text.trim().length() == 0) {
                    assignedCustomersRowSorter.setRowFilter(null);
                } else {
                    assignedCustomersRowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }
            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        assignedCustomersNum = new javax.swing.JLabel();
        assignedCustomersSearchField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        assignedCustomersTable = new javax.swing.JTable();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnBut.setText("Return to Trainer Menu");
        returnBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Customers:");

        assignedCustomersNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        assignedCustomersNum.setText("0");

        assignedCustomersSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignedCustomersSearchFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Search:");

        assignedCustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Name", "Email", "Phone Number", "Fitness Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        assignedCustomersTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(assignedCustomersTable);
        if (assignedCustomersTable.getColumnModel().getColumnCount() > 0) {
            assignedCustomersTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        jLayeredPane8.setBackground(new java.awt.Color(0, 204, 51));
        jLayeredPane8.setForeground(new java.awt.Color(102, 255, 102));
        jLayeredPane8.setOpaque(true);

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oodj_assignment/resources/listcust.png"))); // NOI18N
        jLabel11.setText("Assigned Customers");

        jLayeredPane8.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(377, Short.MAX_VALUE))
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignedCustomersNum)
                .addGap(49, 49, 49))
            .addComponent(jLayeredPane8)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(assignedCustomersSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(assignedCustomersNum))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(assignedCustomersSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButActionPerformed
        // TODO add your handling code here:
        new trainerMenuForm(APUGym, tr_acc).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnButActionPerformed

    private void assignedCustomersSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignedCustomersSearchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignedCustomersSearchFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignedCustomersNum;
    private javax.swing.JTextField assignedCustomersSearchField;
    private javax.swing.JTable assignedCustomersTable;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton returnBut;
    // End of variables declaration//GEN-END:variables
}
